server:
  port: 9081
  servlet:
    context-path: /api
# DataSource Config
spring:
  application:
    name: user-center
  # session 失效时间 1天
  session:
    timeout: 86400
  profiles:
    active: prod
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0